name: Deploy # Workflow 이름
on: 
  push:
    branches:
      - main 
jobs: # Job 설정
  build: 
    runs-on: ubuntu-latest
    env:
        working-directory: ./client
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2
      - name: Check Node v 
        run: node -v
      - name: Install Dependencies 
        run: yarn install --frozen-lockfile
        working-directory: ${{ env.working-directory }}
      - name: Build # React Build
        run: yarn build
        working-directory: ${{ env.working-directory }}
      - name: Build file export
        run: npm run export
        working-directory: ${{ env.working-directory }}
      - name: zip create 
        run: zip -qq -r ./build.zip
        working-directory: ${{ env.working-directory }}
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 ./build.zip s3://hanganggak-client-deploy/./build.zip
      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          --application-name hanganggak-client
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name hanganggak-client
          --s3-location bucket=hanganggak-client-deploy,key=./build.zip,bundleType=zip
